version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-api-dynamo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tqc2wo1ekwd6"
s3_prefix = "sam-api-dynamo"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
